server:
  port: 8080

endpoints:
  restart:
    enabled: true

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

spring:
  jpa:
    hibernate.ddl.auto: create
    generate.ddl: false
    show.sql: true
